CREATE TABLE ITEM_SEQ_LOCK (id INT PRIMARY KEY);
INSERT INTO ITEM_SEQ_LOCK(id) VALUES (1);
INSERT INTO item (id, name) VALUES
    (1, 'Item A'),
    (2, 'Item B'),
    (3, 'Item C');
ALTER SEQUENCE item_seq RESTART WITH (SELECT MAX(id) + 1 FROM item);